import i18n from 'i18next';

const savedLang = typeof localStorage !== 'undefined' ? localStorage.getItem('lang') : null;

const resources = {
  en: {
    translation: {
      welcome_back: 'Welcome Back',
      welcome_back_info: 'Please sign in to continue',
      shop: 'Shop',
      bundles: 'Bundles',
      accessories: 'Accessories',
      nightmarket: 'Night Market',
      profile: 'Profile',
      loadout: 'Loadout',
      gallery: 'Gallery',
      settings: 'Settings',
      owned_items: 'Owned Items',
      inventory: 'Inventory',
      inventory_description:
        'All owned items (skins, buddies, sprays, cards, titles) grouped with visuals from Valorant API.',
      language: 'Language',
      language_en: 'English',
      language_vi: 'Vietnamese',
      account: 'Account',
      display: 'Display',
      settings_description: 'Manage your language and session for this device.',
      language_hint: 'Change the display language for the entire website.',
      logout_hint: 'Clear local tokens and sign in with another Riot account.',
      categories: 'Categories',
      supported_item_types: 'item types supported',
      total_items: 'Total items',
      received_from_riot: 'fetched from Riot',
      refresh: 'Refresh',
      search_placeholder: 'Search by name or description...',
      all: 'All',
      show_all: 'Show all',
      collapse_all: 'Collapse all',
      show: 'Show',
      collapse: 'Collapse',
      no_skins: 'No skins available',
      skins: 'skins',
      noImage: 'No Image',
      no_items_here: 'No items in this category',
      choose_other_category: 'Choose another category or refresh data.',
      prev: 'Prev',
      next: 'Next',
      page: 'Page',
      enable_notifications: 'Enable notifications',
      screenshot_mode: 'Screenshot mode',
      logout: 'Logout',
      levels: 'Levels',
      chromas: 'Chromas',
      select_region: 'Select your region:',
      login_with_riot: 'Login with Riot Games',
      manual_token_label: 'Or paste the URL from the redirect page:',
      manual_token_placeholder: 'Paste URL with access_token here...',
      submit: 'Submit',
      fetching: {
        assets: 'Fetching assets...',
        entitlements_token: 'Fetching entitlements token...',
        user_id: 'Fetching user ID...',
        username: 'Fetching username...',
        storefront: 'Fetching storefront...',
        progress: 'Fetching progress...',
        balances: 'Fetching balances...',
        loadout: 'Fetching loadout...',
        owned_items: 'Fetching owned items...',
      },
    },
  },
  vi: {
    translation: {
      welcome_back: 'Chào mừng trở lại',
      welcome_back_info: 'Vui lòng đăng nhập để tiếp tục',
      shop: 'Cửa hàng',
      bundles: 'Gói',
      accessories: 'Phụ kiện',
      nightmarket: 'Chợ đêm',
      profile: 'Hồ sơ',
      loadout: 'Trang bị',
      gallery: 'Thư viện',
      settings: 'Cài đặt',
      owned_items: 'Vật phẩm sở hữu',
      inventory: 'Kho đồ',
      inventory_description:
        'Toàn bộ vật phẩm bạn sở hữu (skin, buddy, spray, card, title) được gom theo danh mục kèm hình ảnh từ Valorant API.',
      language: 'Ngôn ngữ',
      language_en: 'Tiếng Anh',
      language_vi: 'Tiếng Việt',
      account: 'Tài khoản',
      display: 'Hiển thị',
      settings_description: 'Quản lý ngôn ngữ và phiên đăng nhập trên thiết bị này.',
      language_hint: 'Thay đổi ngôn ngữ hiển thị cho toàn bộ website.',
      logout_hint: 'Xoá token cục bộ và đăng nhập bằng tài khoản Riot khác.',
      categories: 'Danh mục',
      supported_item_types: 'loại item được hỗ trợ',
      total_items: 'Tổng item',
      received_from_riot: 'đã nhận từ Riot',
      refresh: 'Làm mới',
      search_placeholder: 'Tìm theo tên hoặc mô tả...',
      all: 'Tất cả',
      show_all: 'Mở tất cả',
      collapse_all: 'Thu gọn tất cả',
      show: 'Hiển thị',
      collapse: 'Thu gọn',
      no_skins: 'Chưa có skin',
      skins: 'skins',
      noImage: 'Không có ảnh',
      no_items_here: 'Chưa có item ở mục này',
      choose_other_category: 'Chọn danh mục khác hoặc làm mới dữ liệu.',
      prev: 'Trước',
      next: 'Sau',
      page: 'Trang',
      enable_notifications: 'Bật thông báo',
      screenshot_mode: 'Chế độ chụp màn hình',
      logout: 'Đăng xuất',
      levels: 'Cấp độ',
      chromas: 'Màu sắc',
      region: 'Khu vực',
      select_region: 'Chọn khu vực của bạn:',
      login_with_riot: 'Đăng nhập bằng Riot Games',
      manual_token_label: 'Hoặc dán URL từ trang chuyển hướng:',
      manual_token_placeholder: 'Dán URL có chứa access_token vào đây...',
      submit: 'Xác nhận',
      fetching: {
        assets: 'Đang tải tài nguyên...',
        entitlements_token: 'Đang lấy token quyền...',
        user_id: 'Đang lấy ID người dùng...',
        username: 'Đang lấy tên người dùng...',
        storefront: 'Đang lấy cửa hàng...',
        progress: 'Đang lấy tiến trình...',
        balances: 'Đang lấy số dư...',
        loadout: 'Đang lấy trang bị...',
        owned_items: 'Đang lấy vật phẩm sở hữu...',
      },
    },
  },
};

export const getVAPILang = () => {
  const langMap = {
    en: 'en-US',
    vi: 'vi-VN',
    ar: 'ar-AE',
    de: 'de-DE',
    es: 'es-ES',
    fr: 'fr-FR',
    it: 'it-IT',
    jp: 'ja-JP',
    ko: 'ko-KR',
    pl: 'pl-PL',
    pt: 'pt-BR',
    ru: 'ru-RU',
    th: 'th-TH',
    tr: 'tr-TR',
    'zh-Hans': 'zh-CN',
    'zh-Hant': 'zh-TW',
  };
  return langMap[i18n.language] || 'en-US';
};

i18n.init({
  resources,
  lng: savedLang || 'en',
  fallbackLng: 'en',
  debug: false,
  interpolation: {
    escapeValue: false,
  },
});

export default i18n;

